baseURL = "https://ref.finance/"
languageCode = "en-us"
title = "Ref Finance"
theme = "hugo-paper"

params:
	homeInfoParams:
		Title: Ref Finance
		Content: Open Finance on NEAR Protocol
		buttons:
			- name: App
			url: "https://app.ref.finance"
