baseURL: "https://ref.finance/"
languageCode: "en-us"
title: "Ref Finance"
theme: "PaperMod"

minify:
        disableXML: true
        minifyOutput: true

menu:
        main:
          - name: "App"
            identifier: "app"
            url: "https://app.ref.finance"

params:
  env: production
  title: "Ref Finance"
  description: "Open Finance on NAER Protocol"
  
  homeInfoParams:
     Title: "Ref Finance"
     Content: "Open Finance on NEAR Protocol"
     buttons:
             - name: App
               url: "https://app.ref.finance"
